# Stage1 STFT 配置

stft:
  sample_rate: 60000000   # 60MHz（Pluto）
  nperseg: 1024
  hop: 512
  window: hamming
  return_onesided: false
  mag_transform: log1p
  normalize: minmax01
  target_shape: [1024, 1170]

# 目标频率（DJI 5.8GHz 频段）
center_freq: 5805000000   # 5805 MHz
